defmodule GameServerWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :game_server_web

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_game_server_key",
    signing_salt: "G8u1px36",
    same_site: "Lax"
  ]
  socket "/socket", GameServerWeb.UserSocket,
    websocket: [log: false],
    longpoll: false

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options], log: false],
    longpoll: [connect_info: [session: @session_options], log: false]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  # Ensure certain well-known files are handled with strict headers before
  # Plug.Static decides how to serve them (files without extensions need
  # special handling for content-type and compression).
  plug GameServerWeb.Plugs.WellKnown

  plug Plug.Static,
    at: "/",
    from: :game_server_web,
    gzip: not code_reloading?,
    only: GameServerWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :game_server_web
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId

  plug Plug.Telemetry,
    event_prefix: [:phoenix, :endpoint],
    log: {__MODULE__, :access_log_level, []}

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  plug Corsica,
    origins: "*",
    allow_headers: ["content-type", "authorization"],
    allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]

  plug GameServerWeb.Router

  # Used by Plug.Telemetry (Phoenix.Logger) to decide access logging.
  # We keep it global (no per-route logic). Set ACCESS_LOG_LEVEL=false to disable.
  # By default, logs are at :debug so production can stay at Logger :info
  # without emitting per-request logs.
  def access_log_level(_conn) do
    case Application.get_env(:game_server_web, __MODULE__)[:access_log] do
      level when level in [:debug, :info, :warning, :error] -> level
      false -> false
      _ -> :debug
    end
  end
end
