defmodule GameServerWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :game_server_web

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_game_server_key",
    signing_salt: "G8u1px36",
    same_site: "Lax"
  ]
  socket "/socket", GameServerWeb.UserSocket,
    websocket: [log: false],
    longpoll: false

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options], log: false],
    longpoll: [connect_info: [session: @session_options], log: false]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  # Ensure certain well-known files are handled with strict headers before
  # Plug.Static decides how to serve them (files without extensions need
  # special handling for content-type and compression).
  plug GameServerWeb.Plugs.WellKnown

  # Add COOP/COEP headers for Godot 4 web exports (SharedArrayBuffer)
  plug GameServerWeb.Plugs.GameHeaders

  plug Plug.Static,
    at: "/",
    from: :game_server_web,
    gzip: not code_reloading?,
    only: GameServerWeb.static_paths(),
    cache_control_for_etags: "public, max-age=3600",
    cache_control_for_vsn_requests: "public, max-age=31536000, immutable"

  # Serve blog/changelog images early, before the code-reloader
  # and session/CSRF plugs.  This prevents concurrent image requests
  # from being serialized in dev mode.
  plug GameServerWeb.Plugs.ContentStatic

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :game_server_web
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug GameServerWeb.Plugs.RequestTimer

  plug Plug.Telemetry,
    event_prefix: [:phoenix, :endpoint],
    log: {__MODULE__, :access_log_level, []}

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head

  # Skip session for API v1 requests — they use JWT auth, not cookies
  @compiled_session_opts Plug.Session.init(@session_options)
  plug :maybe_session

  defp maybe_session(%{path_info: ["api", "v1" | _]} = conn, _opts), do: conn
  defp maybe_session(conn, _opts), do: Plug.Session.call(conn, @compiled_session_opts)

  # Locale feature temporarily disabled — uncomment when re-enabling
  # plug GameServerWeb.Plugs.LocalePath

  plug GameServerWeb.Plugs.DynamicCors

  plug :dispatch_router

  # Cache the router + compiled init opts in persistent_term to avoid
  # calling router.init([]) on every single request.
  @router_pt_key {__MODULE__, :dispatch_router}
  defp dispatch_router(conn, _opts) do
    {router, init_opts} =
      case :persistent_term.get(@router_pt_key, nil) do
        nil ->
          router = Application.get_env(:game_server_web, :router, GameServerWeb.Router)
          opts = router.init([])
          :persistent_term.put(@router_pt_key, {router, opts})
          {router, opts}

        cached ->
          cached
      end

    router.call(conn, init_opts)
  end

  # Cache the access log level in persistent_term to avoid
  # Application.get_env on every request.
  @access_log_pt_key {__MODULE__, :access_log_level}
  def access_log_level(_conn) do
    case :persistent_term.get(@access_log_pt_key, :not_set) do
      :not_set ->
        level =
          case Application.get_env(:game_server_web, __MODULE__)[:access_log] do
            level when level in [:debug, :info, :warning, :error] -> level
            false -> false
            _ -> :debug
          end

        :persistent_term.put(@access_log_pt_key, level)
        level

      cached ->
        cached
    end
  end
end
