import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :game_server_web, GameServerWeb.Endpoint,
  # Host app builds and serves /assets from root priv/static, not from
  # game_server_web package priv/static.
  cache_static_manifest: {:game_server_host, "priv/static/cache_manifest.json"}

config :game_server_web,
  session_secure: true,
  gzip_static: true

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Purge debug logs at compile-time in production builds.
# Note: this means `Logger.debug/1` calls won't be available in prod without rebuilding.
config :logger, compile_time_purge_matching: [[level_lower_than: :info]]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
